#!/bin/sh

HEADER_STR="Installation of Mizar System Version 7.0.01 (Linux/FPC) (MML 4.01.813)"
LDIR=`pwd`
INSTALL_BIN='/usr/local/bin'
INSTALL_DOC='/usr/local/doc/mizar'
INSTALL_MIZ='/usr/local/share/mizar'

exit_install()
 {
  echo "Installation aborted";
  if test -f install.temp; then rm install.temp; fi;    
  exit 1;
 }

start_install()
 {

   $DIALOG --backtitle "$HEADER_STR" \
   --title Info \
   --textbox README 20 60
   
   $DIALOG --backtitle "$HEADER_STR" \
   --title Executables \
   --inputbox "Enter path where to install Mizar executables \n(use backspace to modify this entry)"  10 60 $INSTALL_BIN 2> install.temp;
   if  [ ! -s install.temp ]; then exit_install; fi
   read INSTALL_BIN < install.temp;
   if [ ! -d $INSTALL_BIN ]; then
     mkdir -p $INSTALL_BIN
     chmod a+r $INSTALL_BIN
   fi
   
   cd $INSTALL_BIN
   gzip -c -d $LDIR/mizbin.tar.gz | tar -xf -
   cd $LDIR

   $DIALOG --backtitle "$HEADER_STR" \
   --title "Shared files" \
   --inputbox "Enter path where to install Mizar shared files \n(use backspace to modify this entry)"  10 60 $INSTALL_MIZ 2> install.temp;
   if  [ ! -s install.temp ]; then exit_install; fi
   read INSTALL_MIZ < install.temp;
   if [ ! -d $INSTALL_MIZ ]
    then
     mkdir -p $INSTALL_MIZ
     chmod a+r $INSTALL_MIZ
    else
     rm -r -f $INSTALL_MIZ/prel/*
     rm -f $INSTALL_MIZ/abstr/*
     rm -f $INSTALL_MIZ/mml/*
     rm -f $INSTALL_MIZ/mizar.dct
     rm -f $INSTALL_MIZ/mizar.dic
     rm -f $INSTALL_MIZ/mizar.msg
     rm -f $INSTALL_MIZ/mml.vct
   fi
   
   $DIALOG --backtitle "$HEADER_STR" \
   --title "Shared files installation" \
   --infobox "It may take some time..."  3 60 ;
   
   cd $INSTALL_MIZ
   gzip -c -d $LDIR/mizshare.tar.gz | tar -xf -
   cd $LDIR
   
   $DIALOG --backtitle "$HEADER_STR" \
   --title "Mizar documentation" \
   --inputbox "Enter path where to install Mizar documentation \n(use backspace to modify this entry)"  10 60 $INSTALL_DOC 2> install.temp;
   if  [ ! -s install.temp ]; then exit_install; fi
   read INSTALL_DOC < install.temp;
   if [ ! -d $INSTALL_DOC ] 
    then
     mkdir -p $INSTALL_DOC
     chmod a+r $INSTALL_DOC
    else 
     rm -f $INSTALL_DOC/*    
   fi
   
   cd $INSTALL_DOC
   gzip -c -d $LDIR/mizdoc.tar.gz | tar -xf -
   cd $LDIR

   $DIALOG --backtitle "$HEADER_STR" \
   --title "Installation completed" \
   --clear \
   --msgbox \
   "\nInstallation process of Mizar System is now completed.\n\n\
Note:\n\n\
Mizar system requires an enviroment variable MIZFILES\n\
which should be set to $INSTALL_MIZ.\n\n\
For details how to set such a variable refer to README.\n\
If $INSTALL_BIN is not on your PATH please do supply it.\n\n\
With questions or comments contact mus@mizar.uwb.edu.pl" 20 80 ;
   rm install.temp;
 }

start_old_install()
 {
   echo " "
   echo "$HEADER_STR"
   echo " "

   echo "Enter path where to install Mizar executables"
   echo "[default is $INSTALL_BIN]"

   if [ "$DEFAULT" != "yes" ]; then
     read ANS
     if [ "$ANS" != "" ]; then INSTALL_BIN=$ANS; fi
   fi

   if [ ! -d $INSTALL_BIN ]; then
     mkdir -p $INSTALL_BIN
     chmod a+r $INSTALL_BIN
   fi

   cd $INSTALL_BIN
   gzip -c -d $LDIR/mizbin.tar.gz | tar -xf -
   cd $LDIR

   echo "Enter path where to install Mizar shared files"
   echo "[default is $INSTALL_MIZ]"

   if [ "$DEFAULT" != "yes" ]; then
     read ANS
     if [ "$ANS" != "" ]; then INSTALL_MIZ=$ANS; fi
   fi

   if [ ! -d $INSTALL_MIZ ] 
    then
     mkdir -p $INSTALL_MIZ
     chmod a+r $INSTALL_MIZ
    else 
     rm -r -f $INSTALL_MIZ/prel/*  
     rm -f $INSTALL_MIZ/abstr/*
     rm -f $INSTALL_MIZ/mml/* 
     rm -f $INSTALL_MIZ/mizar.dct
     rm -f $INSTALL_MIZ/mizar.dic
     rm -f $INSTALL_MIZ/mizar.msg
     rm -f $INSTALL_MIZ/mml.vct      
   fi

   echo "It may take some time..."

   cd $INSTALL_MIZ
   gzip -c -d $LDIR/mizshare.tar.gz | tar -xf -
   cd $LDIR

   echo "Enter path where to install Mizar documentation"
   echo "[default is $INSTALL_DOC]"

   if [ "$DEFAULT" != "yes" ]; then
     read ANS
     if [ "$ANS" != "" ]; then INSTALL_DOC=$ANS; fi
   fi

   if [ ! -d $INSTALL_DOC ] 
    then
     mkdir -p $INSTALL_DOC
     chmod a+r $INSTALL_DOC
    else 
     rm -f $INSTALL_DOC/*    
   fi
   
   cd $INSTALL_DOC
   gzip -c -d $LDIR/mizdoc.tar.gz | tar -xf -
   cd $LDIR

   echo " "
   echo "Installation process of Mizar System is complete."
   echo " "
   echo "Note:"
   echo "Mizar system requires an enviroment variable MIZFILES"
   echo "which should be set to $INSTALL_MIZ. For details how to"
   echo "set such a variable refer to README."  
   echo " "
   echo "If $INSTALL_BIN is not on your PATH please do supply it."
   echo " "
   echo "With questions or comments contact mus@mizar.uwb.edu.pl"
 }

######################## Proper installation #######################
case $1 in
 '--default') DEFAULT="yes"; start_old_install; exit ;;
 '--nodialog') start_old_install; exit ;;
 *)
  OLD_IFS=$IFS;
  IFS=":";
  DIALOG="";
  for d in $PATH; do if test -x $d/dialog; then DIALOG="$d/dialog";break;fi;done; 
  IFS=$OLD_IFS;
  if test "$DIALOG" = ""; then start_old_install; exit; fi;
  $DIALOG --backtitle "$HEADER_STR" \
  --title Start \
  --yesno "Do yo want to start Mizar installation ?" 6 40
  case $? in
   0) start_install ;;
   *) exit_install ;;
  esac;
  ;;
esac;

